resources:
  repositories:
  - repository: self
    type: git
    ref: refs/heads/main
jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    vmImage: ubuntu-latest
  steps:
  - checkout: self
    clean: true
  - task: Bash@3
    displayName: Build extensions
    inputs:
      targetType: inline
      script: >-
        if [ -f extensions.csproj ]

        then
            dotnet build extensions.csproj --output ./bin
        fi
  - task: NodeTool@0
    displayName: Use Node version 10.14.1
    inputs:
      versionSpec: 10.14.1
  - task: Npm@1
    displayName: Install Application Dependencies
    inputs:
      workingDir: $(System.DefaultWorkingDirectory)
      verbose: false
  - task: Npm@1
    displayName: Run 'build' script
    inputs:
      command: custom
      workingDir: $(System.DefaultWorkingDirectory)
      verbose: false
      customCommand: run build --if-present
  - task: Npm@1
    displayName: Remove extraneous packages
    inputs:
      command: custom
      workingDir: $(System.DefaultWorkingDirectory)
      verbose: false
      customCommand: prune --production
  - task: CopyFiles@2
    displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
    inputs:
      SourceFolder: ./build
      TargetFolder: $(build.artifactstagingdirectory)
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
...